# Generated by Django 6.0.4 on 2026-04-14 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilisateurInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('gestionnaire', 'Gestionnaire')], max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Utilisateur interne',
                'verbose_name_plural': 'Utilisateurs internes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
