# Generated by Django 6.0.4 on 2026-04-14 22:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agence', models.CharField(max_length=200)),
                ('nom_responsable', models.CharField(max_length=100)),
                ('prenom_responsable', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('document_justificatif', models.FileField(blank=True, null=True, upload_to='demandes/documents/')),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now)),
                ('traitee', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Demande partenaire',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agence', models.CharField(max_length=200)),
                ('nom_responsable', models.CharField(max_length=100)),
                ('prenom_responsable', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/logos/')),
                ('document_justificatif', models.FileField(blank=True, null=True, upload_to='partenaires/documents/')),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('actif', 'Actif'), ('suspendu', 'Suspendu')], default='en_attente', max_length=20)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.PositiveIntegerField()),
                ('type_vehicule', models.CharField(choices=[('berline', 'Berline'), ('suv', 'SUV'), ('pickup', 'Pick-up'), ('minibus', 'Minibus'), ('citadine', 'Citadine'), ('utilitaire', 'Utilitaire'), ('4x4', '4x4'), ('van', 'Van')], max_length=20)),
                ('couleur', models.CharField(max_length=50)),
                ('nombre_places', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], max_length=20)),
                ('climatisation', models.BooleanField(default=True)),
                ('prix_par_jour', models.DecimalField(decimal_places=0, max_digits=10)),
                ('localisation', models.CharField(max_length=200)),
                ('disponible', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('vues', models.PositiveIntegerField(default=0)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='public.partenaire')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('moyen_paiement', models.CharField(choices=[('cash_livraison', 'Cash à la livraison')], default='cash_livraison', max_length=30)),
                ('cni_recto', models.ImageField(upload_to='reservations/cni/')),
                ('cni_verso', models.ImageField(upload_to='reservations/cni/')),
                ('permis_conduire', models.ImageField(upload_to='reservations/permis/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('motif_refus', models.TextField(blank=True, help_text='Visible uniquement en interne')),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='public.vehicule')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='PhotoVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicules/photos/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='public.vehicule')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
